import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import { AppProvider } from '../../contexts/AppProvider';
import { ExportView } from '../../components/export';
import { useWorkspace } from '../../contexts/WorkspaceContext';
import { useEffect } from 'react';
import type { Strategy } from '../../types/strategy';

const strategies: Strategy[] = [
  {
    title: 'Strategy Alpha',
    why_fits: 'Reason alpha',
    how_to: 'Steps alpha',
    supporting_excerpt: 'Excerpt alpha',
    source_ref: 'Source alpha',
  },
  {
    title: 'Strategy Beta',
    why_fits: 'Reason beta',
    how_to: 'Steps beta',
    supporting_excerpt: 'Excerpt beta',
    source_ref: 'Source beta',
  },
];

function ExportWithSelection({
  selected,
}: {
  selected: number[];
}) {
  const { setStrategies, toggleSelection } = useWorkspace();
  useEffect(() => {
    setStrategies(strategies);
    selected.forEach((i) => toggleSelection(i));
  }, [setStrategies, toggleSelection, selected]);
  return <ExportView />;
}

describe('ExportView', () => {
  it('renders nothing when no strategies are selected', () => {
    const { container } = render(
      <AppProvider>
        <ExportView />
      </AppProvider>,
    );
    expect(container.querySelector('#export-view')).toBeNull();
  });

  it('renders selected strategies', () => {
    render(
      <AppProvider>
        <ExportWithSelection selected={[0]} />
      </AppProvider>,
    );
    expect(screen.getByText('Strategy Alpha')).toBeInTheDocument();
    expect(screen.queryByText('Strategy Beta')).not.toBeInTheDocument();
  });

  it('renders multiple selected strategies', () => {
    render(
      <AppProvider>
        <ExportWithSelection selected={[0, 1]} />
      </AppProvider>,
    );
    expect(screen.getByText('Strategy Alpha')).toBeInTheDocument();
    expect(screen.getByText('Strategy Beta')).toBeInTheDocument();
  });

  it('renders the report header', () => {
    render(
      <AppProvider>
        <ExportWithSelection selected={[0]} />
      </AppProvider>,
    );
    expect(
      screen.getByText('EduNavigator — Strategy Report'),
    ).toBeInTheDocument();
  });

  it('renders the footer', () => {
    render(
      <AppProvider>
        <ExportWithSelection selected={[0]} />
      </AppProvider>,
    );
    expect(
      screen.getByText(/generated by edunavigator/i),
    ).toBeInTheDocument();
  });
});
