import { useLeftRail } from '../../contexts/LeftRailContext';
import { useWorkspace } from '../../contexts/WorkspaceContext';
import { ExportHeader } from './ExportHeader';
import { ExportStrategyPage } from './ExportStrategyPage';

export function ExportView() {
  const { state: context } = useLeftRail();
  const { strategies, selectedIndices } = useWorkspace();

  const selectedStrategies = strategies.filter((_, i) =>
    selectedIndices.has(i),
  );

  if (selectedStrategies.length === 0) return null;

  return (
    <div id="export-view" className="export-view hidden print:block">
      <div className="mx-auto max-w-3xl p-8">
        <ExportHeader context={context} generatedAt={Date.now()} />
        {selectedStrategies.map((strategy, i) => (
          <ExportStrategyPage
            key={`${strategy.title}-${i}`}
            strategy={strategy}
            index={i}
          />
        ))}
        <footer className="mt-8 border-t border-neutral-200 pt-4 text-center text-xs text-neutral-400">
          Generated by EduNavigator — Evidence-Based Strategy Finder
        </footer>
      </div>
    </div>
  );
}
