export function ExportFooter() {
  return (
    <div className="mt-12 border-t border-neutral-200 pt-6 text-center font-[system-ui] text-sm text-neutral-600 print:mt-auto">
      Generated by EduNavigator — Evidence-Based Strategy Finder
    </div>
  );
}
